---
- name: create docker image
  docker_image:
    name: devops
    build:
      path: /var/lib/jenkins/workspace/MyappPipline
      pull: no 
    source: build
    state: present
    force_source: true
-  name: run container docker
   docker_container:
     name: myapp_container
     image: jelassioussema/devops:latest
     state: started
     recreate: true
     ports:
      - "4200:80"


